#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SafeDeal.Android.Resource", IsApplication=true)]

namespace SafeDeal.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideDown = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideRight = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SlideUp = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int common_google_signin_btn_text_dark = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int common_google_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_signin_btn_text_dark_disabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_signin_btn_text_dark_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_signin_btn_text_dark_pressed = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int common_google_signin_btn_text_light = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int common_google_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_signin_btn_text_light_disabled = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_signin_btn_text_light_focused = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_google_signin_btn_text_light_pressed = 2131165191;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonCreateStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignInStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int edit_text_style = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int FavoritesIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int GoogleMaps = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_action_new = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_action_person = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_action_search = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MenuButtons = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ProgressBarStyle = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int sdlogo = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int shake = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sticker = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int xs = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0028
			public const int BtnDialogEmail = 2131361832;
			
			// aapt resource value: 0x7f0a0039
			public const int MoneyButton = 2131361849;
			
			// aapt resource value: 0x7f0a0038
			public const int aboutButton = 2131361848;
			
			// aapt resource value: 0x7f0a0045
			public const int add = 2131361861;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a001d
			public const int amountEditText = 2131361821;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a0023
			public const int btnCreateUser = 2131361827;
			
			// aapt resource value: 0x7f0a0012
			public const int btnHybrid = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int btnNormal = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int btnSat = 2131361811;
			
			// aapt resource value: 0x7f0a002e
			public const int btnSignIn = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int btnSignUp = 2131361839;
			
			// aapt resource value: 0x7f0a003d
			public const int btnStar = 2131361853;
			
			// aapt resource value: 0x7f0a0014
			public const int btnTerrain = 2131361812;
			
			// aapt resource value: 0x7f0a0031
			public const int button1 = 2131361841;
			
			// aapt resource value: 0x7f0a000d
			public const int callTextView = 2131361805;
			
			// aapt resource value: 0x7f0a001c
			public const int cancelButton = 2131361820;
			
			// aapt resource value: 0x7f0a0034
			public const int cartButton = 2131361844;
			
			// aapt resource value: 0x7f0a0037
			public const int closeToYouBtn = 2131361847;
			
			// aapt resource value: 0x7f0a0043
			public const int createUserBtn = 2131361859;
			
			// aapt resource value: 0x7f0a0015
			public const int createUserlistView = 2131361813;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a0017
			public const int dealImageView = 2131361815;
			
			// aapt resource value: 0x7f0a000f
			public const int dealListView = 2131361807;
			
			// aapt resource value: 0x7f0a0018
			public const int dealNameTextView = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int descriptionTextView = 2131361818;
			
			// aapt resource value: 0x7f0a001f
			public const int externalMapButton = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int fragmentContainer = 2131361824;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a003c
			public const int imgPic = 2131361852;
			
			// aapt resource value: 0x7f0a003a
			public const int item_subtitle = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int item_title = 2131361851;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a0032
			public const int logoImageView = 2131361842;
			
			// aapt resource value: 0x7f0a0016
			public const int mainScrollView = 2131361814;
			
			// aapt resource value: 0x7f0a0036
			public const int mapButton = 2131361846;
			
			// aapt resource value: 0x7f0a0010
			public const int mapFrameLayout = 2131361808;
			
			// aapt resource value: 0x7f0a0033
			public const int membersOnlyBtn = 2131361843;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a001e
			public const int orderButton = 2131361822;
			
			// aapt resource value: 0x7f0a000e
			public const int phoneNumberTextView = 2131361806;
			
			// aapt resource value: 0x7f0a001b
			public const int priceTextView = 2131361819;
			
			// aapt resource value: 0x7f0a0024
			public const int progressBar = 2131361828;
			
			// aapt resource value: 0x7f0a0030
			public const int progressBar1 = 2131361840;
			
			// aapt resource value: 0x7f0a0041
			public const int safeDealPictureImageView = 2131361857;
			
			// aapt resource value: 0x7f0a003f
			public const int sample_content_fragment = 2131361855;
			
			// aapt resource value: 0x7f0a003e
			public const int sample_main_layout = 2131361854;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0044
			public const int search = 2131361860;
			
			// aapt resource value: 0x7f0a0019
			public const int shortDescriptionTextView = 2131361817;
			
			// aapt resource value: 0x7f0a0029
			public const int sliding_tabs = 2131361833;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0042
			public const int tabBtn = 2131361858;
			
			// aapt resource value: 0x7f0a0035
			public const int takePictureButton = 2131361845;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0040
			public const int textView1 = 2131361856;
			
			// aapt resource value: 0x7f0a002b
			public const int txtAddress = 2131361835;
			
			// aapt resource value: 0x7f0a002d
			public const int txtCreateAccount = 2131361837;
			
			// aapt resource value: 0x7f0a0026
			public const int txtEmail = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int txtFirstName = 2131361829;
			
			// aapt resource value: 0x7f0a002c
			public const int txtHours = 2131361836;
			
			// aapt resource value: 0x7f0a0021
			public const int txtName = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int txtNumber = 2131361826;
			
			// aapt resource value: 0x7f0a0027
			public const int txtPassword = 2131361831;
			
			// aapt resource value: 0x7f0a002a
			public const int viewpager = 2131361834;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BuyerFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CloseToYouView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateUserMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DealDetailView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DealMapView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DealMenuView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DealRowView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_create_user = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_sign_up = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int FavoriteDealFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_sample = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int info_window = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LoginScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Main = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MainMenu = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int NewUser = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pager_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int row_user = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SellerFragment = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SlidingTabMain = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TakePictureView = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int actionbar = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060015
			public const int ApplicationName = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int Hello = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int closeToYouMsg = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_title = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text_phone = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_text_tablet = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_title = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_notification_ticker = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_unsupported_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_unsupported_title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_button = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_updating_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_updating_title = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_wear_update_text = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int common_open_on_phone = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int common_signin_button_text_long = 2131099667;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CustomActionBarTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MyActionBar = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int dialog_animation = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
